[package]
name = "dicom-ul"
version = "0.7.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>", "Paul Knopf <pauldotknopf@gmail.com>"]
description = "Types and methods for interacting with the DICOM Upper Layer Protocol"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["network-programming"]
keywords = ["dicom", "network"]
readme = "README.md"

[dependencies]
byteordered = "0.6"
bytes = "1.6.1"
dicom-encoding = { path = "../encoding/", version = "0.7.0" }
dicom-transfer-syntax-registry = { path = "../transfer-syntax-registry/", version = "0.7.0", default-features = false }
snafu = "0.8"
tracing = "0.1.34"

[dependencies.tokio]
version = "1.38.0"
optional = true
features = [
    "rt",
    "rt-multi-thread",
    "net",
    "io-util"
]

[dev-dependencies]
matches = "0.1.8"

[features]
async = ["dep:tokio"]
default = []
